language: java
jdk:
  - oraclejdk8
before_install:
  - git config --global user.email "travis-ci@mllnd.xyz"
  - git config --global user.name "Travis CI"
script:
  - './gradlew build'
cache:
  directories:
    - '$HOME/.gradle'
